const content = {
  nav: {
    howItWorks: "How it works",
    calculator: "Calculator",
    pricing: "Tariffs",
    reviews: "Reviews",
    faq: "FAQ",
    contact: "Contact",
    cta: "Get started",
  },
  hero: {
    eyebrow: "CHINA → UZBEKISTAN · AIR CARGO",
    h1: "Your China purchases \u2014 delivered to your door",
    subheadline: "Fast air cargo from China to Uzbekistan. From $9.5/kg. Trusted by 50,000+ customers.",
    ctaPrimary: "Get started now",
    ctaSecondary: "Sign in",
    trust1: "5 years in business",
    trust2: "50,000+ clients",
    trust3: "Air delivery 3\u20137 days",
    channelBadge: "10,000+ subscribers",
    appCaption: "Open the Mandarin Cargo bot",
  },
  trustBar: {
    years: { number: "5", label: "Years experience" },
    clients: { number: "50,000+", label: "Clients" },
    cargo: { number: "160+", label: "Tons delivered" },
    subscribers: { number: "10,000+", label: "Subscribers" },
    paymentTitle: "We accept",
  },
  howItWorks: {
    eyebrow: "PROCESS",
    h2: "Get started in 5 steps",
    subtitle: "All through Telegram \u2014 fast and easy",
    steps: [
      { icon: "Smartphone", title: "Register in bot", desc: "Press /start. Send your name, passport info and photo." },
      { icon: "ShieldCheck", title: "Admin review", desc: "Your data will be confirmed by admin within 24 hours." },
      { icon: "Key", title: "Personal ID code", desc: "You will be given a China warehouse address and personal ID code." },
      { icon: "ShoppingCart", title: "Shop", desc: "Use warehouse address + ID code at Chinese store. Items arrive at warehouse." },
      { icon: "Plane", title: "Delivery", desc: "We air-ship to Tashkent. Pick up or get delivered." },
    ],
    idLabel: "Your personal ID code",
    idCode: "SXXX",
    idCaption: "This code comes with every parcel",
    addressLabel: "Warehouse address in China",
    address: ["SXXX 18161955318", "\u9655\u897f\u7701\u54b8\u9633\u5e02\u6e2d\u57ce\u533a \u5317\u675c\u8857\u9053", "\u662d\u5bb9\u5357\u8857\u4e1c\u822a\u7269\u6d41\u56ed\u5185\u4e2d\u4eac\u4ed3SXXX\u53f7\u4ed3\u5e93"],
  },
  track: {
    eyebrow: "TRACKING",
    h2: "Track your cargo",
    subtitle: "Enter your tracking code — see its status in real time.",
    placeholder: "e.g. SAAS30-12345",
    button: "Track",
    checking: "Checking...",
    weightLabel: "Weight",
    progressLabel: "Completed",
    statusAvailable: "Done",
    statusPending: "In progress",
    statusNodata: "Pending",
    steps: ["At China warehouse", "In transit", "Customs queue", "Sorting", "Ready for pickup", "Picked up"],
    notFound: "Tracking code not found. Please check the code.",
    tooShort: "Tracking code must be at least 3 characters.",
    rateLimit: "Too many requests. Try again in a minute.",
    errorGeneric: "Please check your internet connection — there may be a connection issue.",
  },
  calculator: {
    eyebrow: "CALCULATOR",
    h2: "Calculate your shipping cost",
    subtitle: "From 1 kg, no minimum",
    weightLabel: "Weight (kg)",
    weightPlaceholder: "0.5",
    volumetricToggle: "Volumetric weight",
    volumetricDesc: "If your cargo is large in volume",
    length: "Length",
    width: "Width",
    height: "Height",
    dimPlaceholder: "30",
    dimUnit: "cm",
    submit: "Calculate",
    calculating: "Calculating...",
    resultLabel: "Estimated price:",
    perKg: "$9.5 / kg",
    calculatedWeight: "Chargeable weight",
    real: "Actual",
    volumetric: "Volumetric",
    exchangeRate: "Rate",
    fallbackNotice: "*Estimated calculation. Contact Telegram bot for exact quote.",
    cta: "Register now",
    ctaSub: "Get free personal ID code",
    error: "Please check your internet connection — there may be a connection issue.",
    errorTitle: "Couldn't calculate",
    retry: "Try again",
  },
  features: {
    eyebrow: "WHY US",
    h2: "Why choose us?",
    items: [
      { icon: "DollarSign", title: "Low prices", desc: "From $9.5/kg. No minimum charge. Real air cargo only." },
      { icon: "Plane", title: "Fast delivery", desc: "Air delivery 3\u20137 days to Tashkent. Multiple flights per week." },
      { icon: "MapPin", title: "Live tracking", desc: "Track your cargo in real time via Telegram bot and web cabinet." },
      { icon: "Warehouse", title: "Reliable warehouses", desc: "Own warehouse in China (Shaanxi) and Tashkent office." },
      { icon: "CreditCard", title: "Easy payment", desc: "Click, Payme, Uzum, Alipay, Uzcard, Humo, cash." },
      { icon: "Headphones", title: "Support", desc: "Fast responses via Telegram. Reliable customer service." },
    ],
  },
  pricing: {
    eyebrow: "TARIFFS",
    h2: "Transparent tariffs",
    subtitle: "3 tariffs depending on cargo type. No minimum charge.",
    tiers: [
      {
        name: "Standard cargo",
        price: "$9.5",
        unit: "/ kg",
        desc: "Standard air cargo rate for everyday goods (clothing, electronics, spare parts, etc.).",
      },
      {
        name: "Branded cargo",
        oldPrice: "$13",
        price: "$11",
        unit: "/ kg",
        desc: "For original branded goods (Nike, Adidas, Apple, etc.). Branded cargo is shipped with extra inspection and care, so the rate is slightly higher.",
      },
      {
        name: "Bulk cargo",
        price: "$12",
        unit: "/ kg",
        desc: "If you order more than 3 units of the same product, it counts as commercial (bulk) cargo and is charged at this rate.",
        badges: [
          "Electronics (battery / powered goods)",
          "Cosmetic products",
        ],
      },
    ],
    popularBadge: "Popular",
    includedTitle: "Included in every tariff",
    included: ["Air delivery (3\u20137 days)", "Free storage in China (7 days)", "Live tracking (Telegram + Web)", "China purchasing service (coming soon)", "Cargo insurance"],
    note: "Final price depends on the product type and weight.",
    bonus: "A special bonus is available for volumetric (bulky) cargo.",
    cta: "Calculate",
  },
  reviews: {
    eyebrow: "REVIEWS",
    h2: "Trusted by 50,000+ customers",
    rating: "4.9",
    outOf: "/ 5",
    reviewCount: "1,200+ reviews",
    testimonials: [
      { name: "Dilshod K.", city: "Tashkent", rating: 5, quote: "First time using \u2014 delivered in 5 days. Telegram bot is very convenient." },
      { name: "Nodira R.", city: "Samarkand", rating: 5, quote: "Been using Mandarin Cargo for 5 years. Always reliable." },
      { name: "Akmal B.", city: "Fergana", rating: 5, quote: "Low prices, fast delivery. Great service. Highly recommended!" },
    ],
    screenshotCaption: "Real reviews",
  },
  about: {
    eyebrow: "ABOUT US",
    h2: "5 years of experience, direct China connection",
    intro: "Mandarin Cargo is a service of TRITON SUPPLY CHAIN. For 5 years we have been delivering air cargo from China to Uzbekistan. Our own warehouse is located in Shaanxi Province, China.",
    facts: ["Own warehouse in China (Shaanxi, Xianyang)", "Official company: TRITON SUPPLY CHAIN", "Tashkent office: Chilonzor district, Arnasoy 5A", "Working hours: Mon-Sat 10:00\u201318:30"],
    mapOverlay: "Tashkent, Chilonzor, Arnasoy 5A",
    routeCta: "Directions",
  },
  faq: {
    eyebrow: "FAQ",
    h2: "Frequently asked questions",
    items: [
      { q: "How do I start?", a: "Go to Telegram bot @mandarincargobot and press /start. Registration involves sending personal info (name, passport, photo). After admin confirmation, you receive a personal ID code and China warehouse address." },
      { q: "How long does delivery take?", a: "Air delivery from our China warehouse to Tashkent takes 3\u20137 days. Does not include seller shipping time. Multiple flights per week." },
      { q: "How do I pay?", a: "Click, Payme, Uzum, Alipay, Uzcard, Humo, cash at office. Pay after receiving cargo." },
      { q: "What items cannot be shipped?", a: "Weapons, explosives, drugs, radioactive materials, animals, perishable foods, and restricted imports." },
      { q: "How do I track my cargo?", a: "Via the <bot>Mandarin Cargo bot</bot>: at warehouse \u2192 packed \u2192 flew \u2192 in Tashkent \u2192 delivered." },
      { q: "Why do you need passport info?", a: "Required by Uzbekistan customs law for import declaration. Data is stored securely." },
    ],
  },
  finalCta: {
    h2: "Send your first cargo today",
    subtitle: "Register in the bot in 2 minutes",
    ctaPrimary: "Open Telegram bot",
    ctaSecondary: "Contact admin",
    qrCaption: "Scan in Telegram",
    followUs: "Follow us on social media",
  },
  footer: {
    tagline: "Globally delivered, exceptionally Mandarin",
    siteTitle: "Site",
    contactTitle: "Contact",
    legalTitle: "Legal",
    company: "TRITON SUPPLY CHAIN",
    license: "License: Active",
    copyright: "\u00a9 {year} Mandarin Cargo \u2014 TRITON SUPPLY CHAIN",
    developer: "Developer",
  },
  seo: {
    title: "Air cargo from China to Uzbekistan \u2014 Mandarin Cargo",
    description: "Fast, affordable air cargo from China to Uzbekistan. From $9.5/kg. Register via Telegram bot. Trusted by 50,000+ customers.",
    keywords: ["Mandarin Cargo", "Cargo Mandarin", "Mandarin Cargo Uzbekistan", "Mandarin Cargo Tashkent", "china to uzbekistan cargo", "air cargo", "china warehouse", "uzbekistan delivery", "telegram cargo bot"],
  },
} as const;

export default content;
