const content = {
  nav: {
    howItWorks: "How it works",
    calculator: "Calculator",
    pricing: "Pricing",
    reviews: "Reviews",
    faq: "FAQ",
    contact: "Contact",
    cta: "Get started",
  },
  hero: {
    eyebrow: "CHINA → UZBEKISTAN · AIR CARGO",
    h1: "Your China purchases \u2014 delivered to your door",
    subheadline: "Fast air cargo from China to Uzbekistan. From $9.5/kg. Trusted by 50,000+ customers.",
    ctaPrimary: "Get started now",
    ctaSecondary: "Sign in",
    trust1: "5 years in business",
    trust2: "50,000+ clients",
    trust3: "Air delivery 3\u20137 days",
    channelBadge: "10,000+ subscribers",
  },
  trustBar: {
    years: { number: "5", label: "Years experience" },
    clients: { number: "50,000+", label: "Clients" },
    cargo: { number: "160+", label: "Tons delivered" },
    subscribers: { number: "10,000+", label: "Subscribers" },
    paymentTitle: "We accept",
  },
  howItWorks: {
    eyebrow: "PROCESS",
    h2: "Get started in 5 steps",
    subtitle: "All through Telegram \u2014 fast and easy",
    steps: [
      { icon: "Smartphone", title: "Register in bot", desc: "Press /start. Send your name, passport info and photo." },
      { icon: "ShieldCheck", title: "Admin review", desc: "Your data will be confirmed by admin within 24 hours." },
      { icon: "Key", title: "Personal ID code", desc: "You will be given a China warehouse address and personal ID code." },
      { icon: "ShoppingCart", title: "Shop", desc: "Use warehouse address + ID code at Chinese store. Items arrive at warehouse." },
      { icon: "Plane", title: "Delivery", desc: "We air-ship to Tashkent. Pick up or get delivered." },
    ],
    idLabel: "Your personal ID code",
    idCode: "SXXX",
    idCaption: "This code comes with every parcel",
    addressLabel: "Warehouse address in China",
    address: ["SXXX 18161955318", "\u9655\u897f\u7701\u54b8\u9633\u5e02\u6e2d\u57ce\u533a \u5317\u675c\u8857\u9053", "\u662d\u5bb9\u5357\u8857\u4e1c\u822a\u7269\u6d41\u56ed\u5185\u4e2d\u4eac\u4ed3SXXX\u53f7\u4ed3\u5e93"],
  },
  calculator: {
    eyebrow: "CALCULATOR",
    h2: "Calculate your shipping cost",
    subtitle: "From 1 kg, no minimum",
    weightLabel: "Weight (kg)",
    weightPlaceholder: "0.5",
    volumetricToggle: "Volumetric weight",
    volumetricDesc: "If your cargo is large in volume",
    length: "Length",
    width: "Width",
    height: "Height",
    dimPlaceholder: "0.00",
    dimUnit: "m",
    submit: "Calculate",
    calculating: "Calculating...",
    resultLabel: "Estimated price:",
    perKg: "$9.5 / kg",
    calculatedWeight: "Chargeable weight",
    real: "Actual",
    volumetric: "Volumetric",
    exchangeRate: "Rate",
    fallbackNotice: "*Estimated calculation. Contact Telegram bot for exact quote.",
    cta: "Register now",
    ctaSub: "Get free personal ID code",
    error: "An error occurred. Please try again.",
  },
  features: {
    eyebrow: "WHY US",
    h2: "Why choose us?",
    items: [
      { icon: "DollarSign", title: "Low prices", desc: "From $9.5/kg. No minimum charge. Real air cargo only." },
      { icon: "Plane", title: "Fast delivery", desc: "Air delivery 3\u20137 days to Tashkent. Multiple flights per week." },
      { icon: "MapPin", title: "Live tracking", desc: "Track your cargo in real time via Telegram bot and web cabinet." },
      { icon: "Warehouse", title: "Reliable warehouses", desc: "Own warehouse in China (Shaanxi) and Tashkent office." },
      { icon: "CreditCard", title: "Easy payment", desc: "Click, Payme, Uzum, Alipay, Uzcard, Humo, cash." },
      { icon: "Headphones", title: "Support", desc: "Fast responses via Telegram. Reliable customer service." },
    ],
  },
  pricing: {
    eyebrow: "PRICING",
    h2: "Transparent pricing",
    badge: "AIR CARGO",
    price: "$9.5",
    unit: "/ kg",
    subtitle: "No minimum charge",
    included: ["Air delivery (3\u20137 days)", "Free storage in China (7 days)", "Live tracking (Telegram + Web)", "China purchasing service (coming soon)", "Cargo insurance (coming soon)"],
    gabaritTitle: "How is volumetric weight calculated?",
    gabaritFormula: "L \u00d7 W \u00d7 H (m) \u00d7 167 = volumetric weight (kg)",
    gabaritRule: "The greater of actual and volumetric weight is charged",
    cta: "Calculate",
  },
  reviews: {
    eyebrow: "REVIEWS",
    h2: "Trusted by 50,000+ customers",
    rating: "4.9",
    outOf: "/ 5",
    reviewCount: "1,200+ reviews",
    testimonials: [
      { name: "Dilshod K.", city: "Tashkent", rating: 5, quote: "First time using \u2014 delivered in 5 days. Telegram bot is very convenient." },
      { name: "Nodira R.", city: "Samarkand", rating: 5, quote: "Been using Mandarin Cargo for 5 years. Always reliable." },
      { name: "Akmal B.", city: "Fergana", rating: 5, quote: "Low prices, fast delivery. Great service. Highly recommended!" },
    ],
    screenshotCaption: "Real reviews",
  },
  about: {
    eyebrow: "ABOUT US",
    h2: "5 years of experience, direct China connection",
    intro: "Mandarin Cargo is a service of TRITON SUPPLY CHAIN. For 5 years we have been delivering air cargo from China to Uzbekistan. Our own warehouse is located in Shaanxi Province, China.",
    facts: ["Own warehouse in China (Shaanxi, Xianyang)", "Official company: TRITON SUPPLY CHAIN", "Tashkent office: Chilonzor district, Arnasoy 5A", "Working hours: Mon-Sat 10:00\u201318:30"],
    mapOverlay: "Tashkent, Chilonzor, Arnasoy 5A",
  },
  faq: {
    eyebrow: "FAQ",
    h2: "Frequently asked questions",
    items: [
      { q: "How do I start?", a: "Go to Telegram bot @mandarincargobot and press /start. Registration involves sending personal info (name, passport, photo). After admin confirmation, you receive a personal ID code and China warehouse address." },
      { q: "How long does delivery take?", a: "Air delivery from our China warehouse to Tashkent takes 3\u20137 days. Does not include seller shipping time. Multiple flights per week." },
      { q: "How is price calculated? What is volumetric?", a: "Base rate $9.5/kg. For bulky cargo, volumetric weight is calculated: Length \u00d7 Width \u00d7 Height (m) \u00d7 167. You pay the greater of actual and volumetric weight." },
      { q: "How do I pay?", a: "Click, Payme, Uzum, Alipay, Uzcard, Humo, cash at office. Pay after receiving cargo." },
      { q: "What items cannot be shipped?", a: "Weapons, explosives, drugs, radioactive materials, animals, perishable foods, and restricted imports." },
      { q: "How do I track my cargo?", a: "Via Telegram bot or web cabinet: at warehouse \u2192 packed \u2192 flew \u2192 in Tashkent \u2192 delivered." },
      { q: "Why do you need passport info?", a: "Required by Uzbekistan customs law for import declaration. Data is stored securely." },
    ],
  },
  finalCta: {
    h2: "Send your first cargo today",
    subtitle: "Register in the bot in 2 minutes",
    ctaPrimary: "Open Telegram bot",
    ctaSecondary: "Sign in",
    qrCaption: "Scan in Telegram",
  },
  footer: {
    tagline: "Globally delivered, exceptionally Mandarin",
    siteTitle: "Site",
    contactTitle: "Contact",
    legalTitle: "Legal",
    company: "TRITON SUPPLY CHAIN",
    license: "License: MOCK",
    copyright: "\u00a9 2025 Mandarin Cargo \u2014 TRITON SUPPLY CHAIN",
    admin: "Admin",
  },
  seo: {
    title: "Air cargo from China to Uzbekistan \u2014 Mandarin Cargo",
    description: "Fast, affordable air cargo from China to Uzbekistan. From $9.5/kg. Register via Telegram bot. Trusted by 50,000+ customers.",
    keywords: ["china to uzbekistan cargo", "air cargo", "china warehouse", "uzbekistan delivery", "telegram cargo bot"],
  },
} as const;

export default content;
